//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLager
{
    using System;
    using System.Collections.Generic;
    
    public partial class Meddelanden
    {
        public int Id { get; set; }
        public int AvsändarID { get; set; }
        public int MottagarID { get; set; }
        public string Meddelande { get; set; }
        public Nullable<System.DateTime> Datum { get; set; }
    }
}
