//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLager
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vänner
    {
        public int Frågande { get; set; }
        public int Mottagande { get; set; }
        public bool Accepterad { get; set; }
    
        public virtual Änder FrågandeAnd { get; set; }
        public virtual Änder MottagandeAnd { get; set; }
    }
}
