//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLager
{
    using System;
    using System.Collections.Generic;
    
    public partial class Änder
    {
        public int id { get; set; }
        public string Förnamn { get; set; }
        public string Efternamn { get; set; }
        public string Kön { get; set; }
        public string Ålder { get; set; }
        public string Lösenord { get; set; }
    }
}
